[project]
name = "booknlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filelock>=3.12.0",
    "numpy>=1.24.0",
    "packaging>=23.0",
    "pyyaml>=6.0.1",
    "regex>=2023.8.8",
    "requests>=2.31.0",
    "spacy>=3.5.0",
    "tokenizers>=0.13.0",
    "torch>=2.0.0",
    "tqdm>=4.65.0",
    "transformers>=4.30.0",
]

[dependency-groups]
dev = [
    "pip>=25.2",
    "ruff>=0.12.9",
]
